source 'https://supermarket.chef.io'

metadata

group :delivery do
  cookbook 'delivery_build', git: 'https://github.com/chef-cookbooks/delivery_build'
  cookbook 'delivery-base', git: 'https://github.com/chef-cookbooks/delivery-base'
  cookbook 'habitat-build',  git: 'https://github.com/chef-cookbooks/habitat-build.git', ref: '44f79a329c204f3690dd6dfe4fb319906cdad018'
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
