apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nationalparks-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nationalparks
        env: acceptance
    spec:
      containers:
      - name: nationalparks
        image: ndavidson/national-parks:0.1.4-20170405180227
        ports:
        - containerPort: 8080
        args: ["--peer", "100.96.4.31", "--bind", "database:mongodb.default"]