apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nationalparks-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nationalparks
    spec:
      containers:
      - name: nationalparks
        image: ndavidson/national-parks:latest
        ports:
        - containerPort: 8080
        args: ["--peer", "mongodb-deployment", "--bind", "database:mongodb.default"]