kind: Service
apiVersion: v1
metadata:
  name: nationalparks
spec:
  selector:
    app: nationalparks
    env: acceptance
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080